apiVersion: bindplane.observiq.com/v1beta
kind: SourceType
metadata:
  name: kafka_cluster
  displayName: Kafka Cluster
  description: Kafka cluster metrics scraper, collects metrics from Kafka brokers.
  icon: /icons/sources/kafka.svg
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: cluster_name
      label: Cluster Name
      description: Friendly name used for the resource kafka.cluster.name.
      type: string
      default: ""
      required: true

    - name: protocol_version
      label: Protocol Version
      description: The Kafka protocol version to use when communicating with brokers.
      type: enum
      validValues:
        - "2.2.1"
        - "2.2.0"
        - "2.0.0"
        - "1.0.0"
      default: "2.0.0"

    - name: brokers
      label: Brokers
      description: List of brokers to scrape for metrics.
      type: strings
      default: 
        - localhost:9092
      required: true

    - name: client_id
      label: Client ID
      description: The consumer client ID that the receiver will use.
      type: string
      default: otel-metrics-receiver
      required: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60

    - name: enable_auth
      label: Enable Authentication
      type: bool
      default: false
      advancedConfig: true

    - name: auth_type
      label: Auth Type
      type: enum
      validValues:
        - basic
        - sasl
        # TODO: Should be tested before implemented
        #- tls
        - kerberos
      default: basic
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true    

    - name: basic_username
      label: Username
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: basic    

    - name: basic_password
      label: Password
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: basic    

    - name: sasl_username
      label: Username
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: sasl    

    - name: sasl_password
      label: Password
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: sasl    

    - name: sasl_mechanism
      label: Mechanism
      type: enum
      validValues:
        - SCRAM-SHA-256
        - SCRAM-SHA-512
        - PLAIN
      default: SCRAM-SHA-256
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: sasl    

    - name: kerberos_service_name
      label: Service Name
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos    

    - name: kerberos_realm
      label: Realm
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos    

    - name: kerberos_config_file
      label: Config File
      type: string
      default: /etc/krb5.conf
      required: true 
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos

    - name: kerberos_auth_type
      label: Kerberos Auth Type
      type: enum
      validValues:
        - keytab
        - basic
      default: keytab
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos    

    - name: kerberos_keytab_file
      label: Keytab File
      type: string
      required: true 
      default: /etc/security/kafka.keytab
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos
        - name: kerberos_auth_type
          operator: equals
          value: keytab    

    - name: kerberos_username
      label: Username
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos    
        - name: kerberos_auth_type
          operator: equals
          value: basic    

    - name: kerberos_password
      label: Password
      type: string
      required: true 
      default: ""
      relevantIf:
        - name: enable_auth
          operator: equals
          value: true      
        - name: auth_type
          operator: equals
          value: kerberos    
        - name: kerberos_auth_type
          operator: equals
          value: basic

  metrics:
    receivers: |
      - kafkametrics:
          brokers:
            {{ range $b := .brokers }}
            - {{ $b }}
            {{ end }}
          scrapers:
            - topics
            - consumers
            - brokers
          protocol_version: {{ .protocol_version }}
          client_id: "{{ .client_id }}"
          collection_interval: {{ .collection_interval }}s
          {{ if .enable_auth }}
          auth:
            {{ if eq .auth_type "basic" }}
            plain_text:
              username: "{{ .basic_username }}"
              password: "{{ .basic_password }}"
            {{ else if eq .auth_type "sasl" }}
            sasl:
              username: "{{ .sasl_username }}"
              password: "{{ .sasl_password }}"
              mechanism: {{ .sasl_mechanism }}
            {{ else if eq .auth_type "kerberos" }}
            kerberos:
              service_name: {{ .kerberos_service_name }}
              realm: {{ .kerberos_realm }}
              {{ if eq .kerberos_auth_type "keytab "}}
              use_keytab: true
              keytab_file: {{ .kerberos_keytab_file }}
              {{ else }}
              use_keytab: false
              username: {{ .kerberos_username }}
              password: {{ .kerberos_password }}
              {{ end }}
              config_file: {{ .kerberos_config_file }}
            {{ end }}
          {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]

      - resource:
          attributes:
            - key: kafka.cluster.name
              value: {{ .cluster_name }}
              action: upsert
