apiVersion: bindplane.observiq.com/v1beta
kind: SourceType
metadata:
  name: hana
  displayName: SAP Hana
  icon: /icons/sources/sap.svg
  #description: SAP Hana metrics and logs
  description: SAP Hana logs
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    # # Metrics
    # - name: enable_metrics
    #   label: Metrics
    #   type: bool
    #   default: true

    # - name: collection_interval
    #   label: Collection Interval
    #   description: How often (seconds) to scrape for metrics.
    #   type: int
    #   default: 60
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: address
    #   label: Address
    #   description: IP address or hostname to scrape for JMX metrics.
    #   type: string
    #   default: localhost
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: port
    #   label: Port
    #   description: Port to scrape for JMX metrics.
    #   type: int
    #   default: 33015
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: username
    #   label: Username
    #   description: Username used to authenticate.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: password
    #   label: Password
    #   description: Password used to authenticate.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: enable_tls
    #   label: TLS
    #   type: bool
    #   default: false
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: strict_tls_verify
    #   label: Strict TLS Certificate Verification
    #   description: Enable to require TLS certificate verification.
    #   type: bool
    #   default: false
    #   advancedConfig: true
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true

    # - name: ca_file
    #   label: TLS Certificate Authority File
    #   description: Certificate authority used to validate TLS certificates. Not required if the collector's operating system already trusts the certificate authority.
    #   type: string
    #   required: false
    #   default: ""
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # - name: mutual_tls
    #   label: Mutual TLS Authentication
    #   description: Enable to require TLS mutual authentication.
    #   type: bool
    #   default: false
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # - name: cert_file
    #   label: Mutual TLS Client Certificate File
    #   description: A TLS certificate used for client authentication, if mutual TLS is enabled.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: mutual_tls
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # - name: key_file
    #   label: Mutual TLS Client Private Key File
    #   description: A TLS private key used for client authentication, if mutual TLS is enabled.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: mutual_tls
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # Logs
    - name: enable_logs
      label: Logs
      type: bool
      default: true

    - name: file_path
      label: Log Path(s)
      description: File paths to logs.
      type: strings
      default:
        - "/usr/sap/*/HDB*/*/trace/*.trc"
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: enum
      default: "UTC"
      validValues: ["UTC","Africa/Abidjan","Africa/Accra","Africa/Addis_Ababa","Africa/Algiers","Africa/Asmara","Africa/Bamako","Africa/Bangui","Africa/Banjul","Africa/Bissau","Africa/Blantyre","Africa/Brazzaville","Africa/Bujumbura","Africa/Cairo","Africa/Casablanca","Africa/Ceuta","Africa/Conakry","Africa/Dakar","Africa/Dar_es_Salaam","Africa/Djibouti","Africa/Douala","Africa/El_Aaiun","Africa/Freetown","Africa/Gaborone","Africa/Harare","Africa/Johannesburg","Africa/Juba","Africa/Kampala","Africa/Khartoum","Africa/Kigali","Africa/Kinshasa","Africa/Lagos","Africa/Libreville","Africa/Lome","Africa/Luanda","Africa/Lubumbashi","Africa/Lusaka","Africa/Malabo","Africa/Maputo","Africa/Maseru","Africa/Mbabane","Africa/Mogadishu","Africa/Monrovia","Africa/Nairobi","Africa/Ndjamena","Africa/Niamey","Africa/Nouakchott","Africa/Ouagadougou","Africa/Porto-Novo","Africa/Sao_Tome","Africa/Tripoli","Africa/Tunis","Africa/Windhoek","America/Adak","America/Anchorage","America/Anguilla","America/Antigua","America/Araguaina","America/Argentina/Buenos_Aires","America/Argentina/Catamarca","America/Argentina/Cordoba","America/Argentina/Jujuy","America/Argentina/La_Rioja","America/Argentina/Mendoza","America/Argentina/Rio_Gallegos","America/Argentina/Salta","America/Argentina/San_Juan","America/Argentina/San_Luis","America/Argentina/Tucuman","America/Argentina/Ushuaia","America/Aruba","America/Asuncion","America/Atikokan","America/Bahia","America/Bahia_Banderas","America/Barbados","America/Belem","America/Belize","America/Blanc-Sablon","America/Boa_Vista","America/Bogota","America/Boise","America/Cambridge_Bay","America/Campo_Grande","America/Cancun","America/Caracas","America/Cayenne","America/Cayman","America/Chicago","America/Chihuahua","America/Costa_Rica","America/Creston","America/Cuiaba","America/Curacao","America/Danmarkshavn","America/Dawson","America/Dawson_Creek","America/Denver","America/Detroit","America/Dominica","America/Edmonton","America/Eirunepe","America/El_Salvador","America/Fort_Nelson","America/Fortaleza","America/Glace_Bay","America/Goose_Bay","America/Grand_Turk","America/Grenada","America/Guadeloupe","America/Guatemala","America/Guayaquil","America/Guyana","America/Halifax","America/Havana","America/Hermosillo","America/Indiana/Indianapolis","America/Indiana/Knox","America/Indiana/Marengo","America/Indiana/Petersburg","America/Indiana/Tell_City","America/Indiana/Vevay","America/Indiana/Vincennes","America/Indiana/Winamac","America/Inuvik","America/Iqaluit","America/Jamaica","America/Juneau","America/Kentucky/Louisville","America/Kentucky/Monticello","America/Kralendijk","America/La_Paz","America/Lima","America/Los_Angeles","America/Lower_Princes","America/Maceio","America/Managua","America/Manaus","America/Marigot","America/Martinique","America/Matamoros","America/Mazatlan","America/Menominee","America/Merida","America/Metlakatla","America/Mexico_City","America/Miquelon","America/Moncton","America/Monterrey","America/Montevideo","America/Montserrat","America/Nassau","America/New_York","America/Nipigon","America/Nome","America/Noronha","America/North_Dakota/Beulah","America/North_Dakota/Center","America/North_Dakota/New_Salem","America/Nuuk","America/Ojinaga","America/Panama","America/Pangnirtung","America/Paramaribo","America/Phoenix","America/Port-au-Prince","America/Port_of_Spain","America/Porto_Velho","America/Puerto_Rico","America/Punta_Arenas","America/Rainy_River","America/Rankin_Inlet","America/Recife","America/Regina","America/Resolute","America/Rio_Branco","America/Santarem","America/Santiago","America/Santo_Domingo","America/Sao_Paulo","America/Scoresbysund","America/Sitka","America/St_Barthelemy","America/St_Johns","America/St_Kitts","America/St_Lucia","America/St_Thomas","America/St_Vincent","America/Swift_Current","America/Tegucigalpa","America/Thule","America/Thunder_Bay","America/Tijuana","America/Toronto","America/Tortola","America/Vancouver","America/Whitehorse","America/Winnipeg","America/Yakutat","America/Yellowknife","Antarctica/Casey","Antarctica/Davis","Antarctica/DumontDUrville","Antarctica/Macquarie","Antarctica/Mawson","Antarctica/McMurdo","Antarctica/Palmer","Antarctica/Rothera","Antarctica/Syowa","Antarctica/Troll","Antarctica/Vostok","Arctic/Longyearbyen","Asia/Aden","Asia/Almaty","Asia/Amman","Asia/Anadyr","Asia/Aqtau","Asia/Aqtobe","Asia/Ashgabat","Asia/Atyrau","Asia/Baghdad","Asia/Bahrain","Asia/Baku","Asia/Bangkok","Asia/Barnaul","Asia/Beirut","Asia/Bishkek","Asia/Brunei","Asia/Chita","Asia/Choibalsan","Asia/Colombo","Asia/Damascus","Asia/Dhaka","Asia/Dili","Asia/Dubai","Asia/Dushanbe","Asia/Famagusta","Asia/Gaza","Asia/Hebron","Asia/Ho_Chi_Minh","Asia/Hong_Kong","Asia/Hovd","Asia/Irkutsk","Asia/Jakarta","Asia/Jayapura","Asia/Jerusalem","Asia/Kabul","Asia/Kamchatka","Asia/Karachi","Asia/Kathmandu","Asia/Khandyga","Asia/Kolkata","Asia/Krasnoyarsk","Asia/Kuala_Lumpur","Asia/Kuching","Asia/Kuwait","Asia/Macau","Asia/Magadan","Asia/Makassar","Asia/Manila","Asia/Muscat","Asia/Nicosia","Asia/Novokuznetsk","Asia/Novosibirsk","Asia/Omsk","Asia/Oral","Asia/Phnom_Penh","Asia/Pontianak","Asia/Pyongyang","Asia/Qatar","Asia/Qostanay","Asia/Qyzylorda","Asia/Riyadh","Asia/Sakhalin","Asia/Samarkand","Asia/Seoul","Asia/Shanghai","Asia/Singapore","Asia/Srednekolymsk","Asia/Taipei","Asia/Tashkent","Asia/Tbilisi","Asia/Tehran","Asia/Thimphu","Asia/Tokyo","Asia/Tomsk","Asia/Ulaanbaatar","Asia/Urumqi","Asia/Ust-Nera","Asia/Vientiane","Asia/Vladivostok","Asia/Yakutsk","Asia/Yangon","Asia/Yekaterinburg","Asia/Yerevan","Atlantic/Azores","Atlantic/Bermuda","Atlantic/Canary","Atlantic/Cape_Verde","Atlantic/Faroe","Atlantic/Madeira","Atlantic/Reykjavik","Atlantic/South_Georgia","Atlantic/St_Helena","Atlantic/Stanley","Australia/Adelaide","Australia/Brisbane","Australia/Broken_Hill","Australia/Currie","Australia/Darwin","Australia/Eucla","Australia/Hobart","Australia/Lindeman","Australia/Lord_Howe","Australia/Melbourne","Australia/Perth","Australia/Sydney","Europe/Amsterdam","Europe/Andorra","Europe/Astrakhan","Europe/Athens","Europe/Belgrade","Europe/Berlin","Europe/Bratislava","Europe/Brussels","Europe/Bucharest","Europe/Budapest","Europe/Busingen","Europe/Chisinau","Europe/Copenhagen","Europe/Dublin","Europe/Gibraltar","Europe/Guernsey","Europe/Helsinki","Europe/Isle_of_Man","Europe/Istanbul","Europe/Jersey","Europe/Kaliningrad","Europe/Kiev","Europe/Kirov","Europe/Lisbon","Europe/Ljubljana","Europe/London","Europe/Luxembourg","Europe/Madrid","Europe/Malta","Europe/Mariehamn","Europe/Minsk","Europe/Monaco","Europe/Moscow","Europe/Oslo","Europe/Paris","Europe/Podgorica","Europe/Prague","Europe/Riga","Europe/Rome","Europe/Samara","Europe/San_Marino","Europe/Sarajevo","Europe/Saratov","Europe/Simferopol","Europe/Skopje","Europe/Sofia","Europe/Stockholm","Europe/Tallinn","Europe/Tirane","Europe/Ulyanovsk","Europe/Uzhgorod","Europe/Vaduz","Europe/Vatican","Europe/Vienna","Europe/Vilnius","Europe/Volgograd","Europe/Warsaw","Europe/Zagreb","Europe/Zaporozhye","Europe/Zurich","Indian/Antananarivo","Indian/Chagos","Indian/Christmas","Indian/Cocos","Indian/Comoro","Indian/Kerguelen","Indian/Mahe","Indian/Maldives","Indian/Mauritius","Indian/Mayotte","Indian/Reunion","Pacific/Apia","Pacific/Auckland","Pacific/Bougainville","Pacific/Chatham","Pacific/Chuuk","Pacific/Easter","Pacific/Efate","Pacific/Enderbury","Pacific/Fakaofo","Pacific/Fiji","Pacific/Funafuti","Pacific/Galapagos","Pacific/Gambier","Pacific/Guadalcanal","Pacific/Guam","Pacific/Honolulu","Pacific/Kiritimati","Pacific/Kosrae","Pacific/Kwajalein","Pacific/Majuro","Pacific/Marquesas","Pacific/Midway","Pacific/Nauru","Pacific/Niue","Pacific/Norfolk","Pacific/Noumea","Pacific/Pago_Pago","Pacific/Palau","Pacific/Pitcairn","Pacific/Pohnpei","Pacific/Port_Moresby","Pacific/Rarotonga","Pacific/Saipan","Pacific/Tahiti","Pacific/Tarawa","Pacific/Tongatapu","Pacific/Wake","Pacific/Wallis"]
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: start_at
      label: Start At
      description: Start reading file from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

  # metrics:
  #   receivers: |
  #     {{ if .enable_metrics }}
  #     - saphana:
  #         endpoint: {{ .address }}:{{ .port }}
  #         collection_interval: {{ .collection_interval }}s
  #         username: {{ .username }}
  #         password: {{ .password }}

  #         tls:
  #         {{ if .enable_tls }}
  #           insecure: false
  #           {{ if .strict_tls_verify }}
  #           insecure_skip_verify: false
  #           {{ if .ca_file }}
  #           ca_file: {{ .ca_file }}
  #           {{ end }}
  #           {{ else }}
  #           insecure_skip_verify: true
  #           {{ end }}
  #           {{ if .mutual_tls }}
  #           cert_file: "{{ .cert_file }}"
  #           key_file: "{{ .key_file }}"
  #           {{ end }}
  #         {{ else }}
  #           insecure: true
  #         {{ end }}
  #     {{ end }}

  #   processors: |
  #     - resourcedetection:
  #         detectors: ["system"]
  #         system:
  #           hostname_sources: ["os"]

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/sap_hana_logs.yaml
          parameters:
            start_at: {{ .start_at }}
            timezone: {{ .timezone }}
            file_path:
              {{ range $fp := .file_path }}
              - '{{ $fp }}'
              {{ end }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
