apiVersion: bindplane.observiq.com/v1beta
kind: SourceType
metadata:
  name: vmware_vcenter
  displayName: VMare vCenter
  icon: /icons/sources/vmware_vcenter.svg
  description: VMware vCenter metrics and syslog
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_port
      label: Listening Port
      description: The port to bind to and receive syslog. Collector must be running as root (Linux) or Administrator (windows) when binding to a port below 1024.
      type: int
      default: 5140
      required: true

    - name: listen_ip
      label: Listening IP Address
      description: The IP address to bind to and receive syslog.
      type: string
      default: "0.0.0.0"
      advancedConfig: true

    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      advancedConfig: true

    - name: cert_file
      label: TLS Certificate File
      description: Path to the x509 PEM certificate.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: TLS Private Key File
      description: Path to the x509 PEM private key.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

  logs:
    receivers: |
      - plugin/esxi:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/esxi_logs.yaml
          parameters:
            listen_port: {{ .listen_port }}
            listen_ip: {{ .listen_ip }}
            {{ if .enable_tls }}
            enable_tls: {{ .enable_tls }}
            certificate_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
