apiVersion: bindplane.observiq.com/v1beta
kind: DestinationType
metadata:
  name: zipkin
  displayName: Zipkin
  icon: /icons/destinations/zipkin.svg
spec:
  parameters:
    - name: hostname
      label: Hostname
      description: Hostname or IP address of the Zipkin server.
      type: string
      default: ""
      required: true

    - name: port
      label: Port
      description: Port (gRPC) of the Zipkin server.
      type: int
      default: 9411

    - name: path
      label: Path
      description: API path to send traces to.
      type: string
      default: "/api/v2/spans"
      required: true

    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority file used to validate TLS certificates. Required only if the underlying operating system does not trust Zipkin's certificate.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
        - name: insecure_skip_verify
          operator: equals
          value: false
      advancedConfig: true

    - name: mutual_tls
      label: Mutual TLS
      description: Whether or not to use mutual TLS authentication.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

  traces:
    exporters: |
      - zipkin:
          {{ if .enable_tls }}
          endpoint: https://{{ .hostname }}:{{ .port }}{{ .path }}
          {{ else }}
          endpoint: http://{{ .hostname }}:{{ .port }}{{ .path }}
          {{ end }}
          tls:
          {{ if .enable_tls }}
            insecure: false
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            {{ if .mutual_tls }}
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            {{ end }}
          {{ else }}
            insecure: true
          {{ end }}

    processors: |
      - batch:
