apiVersion: bindplane.observiq.com/v1beta
kind: ProcessorType
metadata:
  name: add_attribute
  displayName: Add Attribute
spec:
  version: 0.0.1
  parameters:
    - name: attributes
      label: Map Type Param
      type: map
      required: true

    - name: action
      label: Action
      type: enum
      description: 'insert: Add attribute if it does not exist. update: Update existing value. upsert: Insert or update.'
      default: upsert
      validValues:
        - insert
        - update
        - upsert

    - name: enable_metrics
      label: Enable Metrics
      type: bool
      default: true

    - name: enable_logs
      label: Enable Logs
      type: bool
      default: true

    - name: enable_traces
      label: Enable Traces`
      type: bool
      default: true

  metrics:
    processors: |
      {{ if .enable_metrics }}
      - attributes:
          actions:
            {{ range $k, $v := .attributes }}
            - key: '{{ $k }}'
              value: '{{ $v }}'
              action: upsert
            {{ end }}
      {{ end }}

  logs:
    processors: |
      {{ if .enable_logs }}
      - attributes:
          actions:
            {{ range $k, $v := .attributes }}
            - key: '{{ $k }}'
              value: '{{ $v }}'
              action: upsert
            {{ end }}
      {{ end }}

  traces:
    processors: |
      {{ if .enable_traces }}
      - attributes:
          actions:
            {{ range $k, $v := .attributes }}
            - key: '{{ $k }}'
              value: '{{ $v }}'
              action: upsert
            {{ end }}
      {{ end }}
