apiVersion: bindplane.observiq.com/v1beta
kind: ProcessorType
metadata:
  name: delete_attribute
  displayName: Delete Attribute
spec:
  version: 0.0.1
  parameters:
    - name: attributes
      label: Attribute Keys
      type: strings
      required: true

    - name: enable_metrics
      label: Enable Metrics
      type: bool
      default: true

    - name: enable_logs
      label: Enable Logs
      type: bool
      default: true

    - name: enable_traces
      label: Enable Traces
      type: bool
      default: true

  metrics:
    processors: |
      {{ if .enable_metrics }}
      - attributes:
          actions:
            {{ range $k := .attributes }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
      {{ end }}

  logs:
    processors: |
      {{ if .enable_logs }}
      - attributes:
          actions:
            {{ range $k := .attributes }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
      {{ end }}

  traces:
    processors: |
      {{ if .enable_traces }}
      - attributes:
          actions:
            {{ range $k := .attributes }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
      {{ end }}
