name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.7.1'
        with:
          credentials_json: '${{ secrets.GCP_DEV_SA_KEY }}'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Cache Go
        id: module-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache NPM
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ui/node_modules
          key: npm-cache-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: npm-cache-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: v1.9.0
          args: release --rm-dist --parallelism 1
        env:
          # github token requires permission to observiq/bindplane and observiq/homebrew-bindplane
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
